# codemagic.yaml

workflows:
  build-ethilia-apk:
    name: Build Ethilia Android APK
    environment:
      flutter: false
      xcode: false
      android: true
    scripts:
      - name: Clean Briefcase build
        script: |
          briefcase clean android
      - name: Install Briefcase
        script: |
          pip install briefcase
      - name: Build APK
        script: |
          briefcase create android
          briefcase build android
    artifacts:
      - .ethilia/android/gradle/app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - getfukd4269@gmail.com
        notify:
          success: true
          failure: true
