# codemagic.yaml

workflows:
  build_ethilia_apk:   # ✅ change dash to underscore
    name: Build Ethilia Android APK
    environment:
      vars:
        BRIEFCASE_PLATFORM: "android"
scripts:
  - name: Install Briefcase
    script: |
      pip install briefcase

  - name: Clean Briefcase build
    script: |
      briefcase clean android

  - name: Build APK
    script: |
      briefcase create android
      briefcase build android
artifacts:
  - "**/app-debug.apk"
    publishing:
      email:
        recipients:
          - getfukd4269@gmail.com
        notify:
          success: true
          failure: true
