# codemagic.yaml

workflows:
  build_ethilia_apk:
    name: Build Ethilia APK (32-bit)
    environment:
      vars:
        BRIEFCASE_ANDROID_ABIS: armeabi-v7a
    scripts:
      - name: Install dependencies
        script: |
          pip install --upgrade pip
          pip install briefcase
      - name: Create Android project
        script: briefcase create android
      - name: Build Android project
        script: briefcase build android
      - name: Package Android APK
        script: briefcase package android
    artifacts:
      - "dist/*.apk"
    publishing:
      email:
        recipients:
          - "getfukd4269@gmail.com"
